name: Challenge Backend
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PYTHON_VERSION: 3.13
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SNS_TOPIC_CATALOG_ARN: ${{ secrets.SNS_TOPIC_CATALOG_ARN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Install poetry
        run: |
          pipx install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run task test